server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # Ele é o servidor, não precisa se registrar nele mesmo
    fetch-registry: false